"""Analysis utilities: turn eval_results.csv into paper assets.

Three responsibilities:
  * Load and validate the results CSV.
  * Pivot/aggregate it for the figures and tables.
  * Render LaTeX tables (booktabs) and matplotlib PDFs sized for ACL.

Display names and ordering live at the top of this module. Edit them to
match the paper's voice.
"""
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)


# Display names for paper context. The "(ours)" tag goes on Run B because
# that's the contribution the paper centers on.
VARIANT_DISPLAY = {
    "runA-truncate": "MNRL + truncate",
    "runA-pca": "MNRL + PCA",
    "runB-truncate": "MRL + truncate (ours)",
    "nomic-truncate": "Nomic Embed v1.5",
}

VARIANT_ORDER = [
    "runA-truncate",
    "runA-pca",
    "runB-truncate",
    "nomic-truncate",
]

DATASET_DISPLAY = {
    "scifact": "SciFact",
    "nfcorpus": "NFCorpus",
    "arguana": "ArguAna",
    "fiqa": "FiQA",
    "trec-covid": "TREC-COVID",
}

DATASET_ORDER = ["scifact", "nfcorpus", "arguana", "fiqa", "trec-covid"]

# ACL paper figure sizing (inches)
ACL_COL_WIDTH = 3.3
ACL_FULL_WIDTH = 6.85


def load_results(csv_path: str | Path) -> pd.DataFrame:
    """Load eval_results.csv and validate schema + content."""
    df = pd.read_csv(csv_path)
    expected_cols = {"variant", "dim", "dataset",
                     "ndcg_at_10", "recall_at_100", "map_at_10"}
    missing = expected_cols - set(df.columns)
    if missing:
        raise ValueError(f"missing columns in {csv_path}: {missing}")
    return df


def pivot_variants_x_dims(
    df: pd.DataFrame, metric: str = "ndcg_at_10"
) -> pd.DataFrame:
    """Variants × dims, values are mean(metric) over the 5 BEIR datasets."""
    pivot = df.groupby(["variant", "dim"])[metric].mean().unstack("dim")
    return pivot.reindex(VARIANT_ORDER)


def pivot_datasets_x_variants_at_dim(
    df: pd.DataFrame, dim: int, metric: str = "ndcg_at_10"
) -> pd.DataFrame:
    """Datasets × variants at a fixed dim. No averaging."""
    sub = df[df["dim"] == dim]
    pivot = sub.pivot(index="dataset", columns="variant", values=metric)
    return pivot.reindex(index=DATASET_ORDER, columns=VARIANT_ORDER)


def _metric_label(metric: str) -> str:
    return {
        "ndcg_at_10": "nDCG@10",
        "recall_at_100": "Recall@100",
        "map_at_10": "MAP@10",
    }.get(metric, metric)


def setup_matplotlib_acl() -> None:
    """Configure matplotlib for ACL-style figures.

    Single column = 3.3 inches wide, serif font, editable PDF text.
    Falls back to DejaVu Serif if Times is not installed (Windows often lacks it).
    """
    import matplotlib.pyplot as plt
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
        "font.size": 8,
        "axes.titlesize": 9,
        "axes.labelsize": 9,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "legend.fontsize": 7,
        "lines.linewidth": 1.2,
        "lines.markersize": 4,
        "axes.linewidth": 0.6,
        "xtick.major.width": 0.6,
        "ytick.major.width": 0.6,
        "figure.dpi": 200,
        "savefig.dpi": 300,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


# ------------------- LaTeX table writers -------------------

def _bold_if_max(value: float, max_val: float, fmt: str = ".4f", tol: float = 1e-6) -> str:
    s = f"{value:{fmt}}"
    if abs(value - max_val) < tol:
        return f"\\textbf{{{s}}}"
    return s


def write_main_results_table(
    df: pd.DataFrame, out_path: Path, metric: str = "ndcg_at_10"
) -> None:
    """Variants × dims, mean metric across datasets. Column-max bolded.

    Bolding the column max means: for each dimension, which method wins.
    """
    pivot = pivot_variants_x_dims(df, metric=metric)
    pivot = pivot[sorted(pivot.columns, reverse=True)]  # 768 leftmost

    n_dims = len(pivot.columns)
    lines = [
        r"% Auto-generated by 06_make_tables.py. Do not edit by hand.",
        r"\begin{tabular}{l" + "r" * n_dims + r"}",
        r"\toprule",
    ]
    header = ["Method"] + [f"$d{{=}}{int(d)}$" for d in pivot.columns]
    lines.append(" & ".join(header) + r" \\")
    lines.append(r"\midrule")

    col_maxes = {d: pivot[d].max() for d in pivot.columns}

    for variant in VARIANT_ORDER:
        cells = [VARIANT_DISPLAY[variant]]
        for dim in pivot.columns:
            v = pivot.loc[variant, dim]
            cells.append(_bold_if_max(v, col_maxes[dim]))
        lines.append(" & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_per_dataset_table(
    df: pd.DataFrame, out_path: Path, dim: int = 32, metric: str = "ndcg_at_10"
) -> None:
    """Datasets × variants at fixed dim. Row-max bolded (winning method per dataset)."""
    pivot = pivot_datasets_x_variants_at_dim(df, dim=dim, metric=metric)

    n_vars = len(VARIANT_ORDER)
    lines = [
        r"% Auto-generated by 06_make_tables.py. Do not edit by hand.",
        r"\begin{tabular}{l" + "r" * n_vars + r"}",
        r"\toprule",
    ]
    header = ["Dataset"] + [VARIANT_DISPLAY[v] for v in VARIANT_ORDER]
    lines.append(" & ".join(header) + r" \\")
    lines.append(r"\midrule")

    for ds in DATASET_ORDER:
        row_vals = pivot.loc[ds].values
        row_max = row_vals.max()
        cells = [DATASET_DISPLAY[ds]]
        for v in row_vals:
            cells.append(_bold_if_max(v, row_max))
        lines.append(" & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_mrl_vs_pca_table(
    df: pd.DataFrame, out_path: Path, metric: str = "ndcg_at_10"
) -> None:
    """Per-dim head-to-head: Run B + truncate vs Run A + PCA. Mean across datasets.

    The $\\Delta$ column is bolded when MRL wins (> 0).
    """
    sub = df[df["variant"].isin(["runA-pca", "runB-truncate"])]
    pivot = sub.groupby(["variant", "dim"])[metric].mean().unstack("variant")
    pivot["gap"] = pivot["runB-truncate"] - pivot["runA-pca"]
    pivot = pivot.sort_index(ascending=False)

    lines = [
        r"% Auto-generated by 06_make_tables.py. Do not edit by hand.",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Dim & MRL + truncate & MNRL + PCA & $\Delta$ \\",
        r"\midrule",
    ]
    for dim, row in pivot.iterrows():
        b = row["runB-truncate"]
        p = row["runA-pca"]
        gap = row["gap"]
        gap_str = f"{gap:+.4f}"
        if gap > 0:
            gap_str = f"\\textbf{{{gap_str}}}"
        lines.append(f"{int(dim)} & {b:.4f} & {p:.4f} & {gap_str} " + r"\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ------------------- matplotlib plot writers -------------------

# Color and marker per variant. Run B (the contribution) gets red.
_VARIANT_COLORS = {
    "runA-truncate": "#888888",
    "runA-pca": "#1f77b4",
    "runB-truncate": "#d62728",
    "nomic-truncate": "#2ca02c",
}
_VARIANT_MARKERS = {
    "runA-truncate": "s",
    "runA-pca": "^",
    "runB-truncate": "o",
    "nomic-truncate": "D",
}


def plot_ndcg_vs_dim(
    df: pd.DataFrame, out_path: Path, metric: str = "ndcg_at_10"
) -> None:
    """Headline figure: avg metric vs dim, one line per variant. Log-x scale."""
    import matplotlib.pyplot as plt
    setup_matplotlib_acl()

    pivot = pivot_variants_x_dims(df, metric=metric)
    dims = sorted(pivot.columns)

    fig, ax = plt.subplots(figsize=(ACL_COL_WIDTH, ACL_COL_WIDTH * 0.75))

    for variant in VARIANT_ORDER:
        values = [pivot.loc[variant, d] for d in dims]
        ax.plot(
            dims, values,
            marker=_VARIANT_MARKERS[variant],
            color=_VARIANT_COLORS[variant],
            label=VARIANT_DISPLAY[variant],
        )

    ax.set_xscale("log", base=2)
    ax.set_xticks(dims)
    ax.set_xticklabels([str(d) for d in dims])
    ax.set_xlabel("Embedding dimension")
    ax.set_ylabel(f"Avg {_metric_label(metric)}")
    ax.legend(loc="lower right", framealpha=0.92, edgecolor="black", fancybox=False)
    ax.grid(True, alpha=0.3, linewidth=0.5)
    ax.set_axisbelow(True)

    fig.tight_layout()
    fig.savefig(out_path, format="pdf", bbox_inches="tight")
    plt.close(fig)


def plot_per_dataset_heatmap(
    df: pd.DataFrame,
    out_path: Path,
    variant: str = "runB-truncate",
    metric: str = "ndcg_at_10",
) -> None:
    """% retention vs dim=768, dataset rows × dim cols, single variant."""
    import matplotlib.pyplot as plt
    setup_matplotlib_acl()

    sub = df[df["variant"] == variant].copy()
    pivot = sub.pivot(index="dataset", columns="dim", values=metric)

    full = pivot[768]
    pct = pivot.div(full, axis=0) * 100

    pct = pct.reindex(
        index=DATASET_ORDER,
        columns=sorted(pct.columns, reverse=True),
    )

    fig, ax = plt.subplots(figsize=(ACL_COL_WIDTH * 1.15, ACL_COL_WIDTH * 0.75))
    im = ax.imshow(pct.values, aspect="auto", cmap="RdYlGn", vmin=20, vmax=100)

    ax.set_xticks(range(len(pct.columns)))
    ax.set_xticklabels([str(int(d)) for d in pct.columns])
    ax.set_yticks(range(len(pct.index)))
    ax.set_yticklabels([DATASET_DISPLAY[d] for d in pct.index])
    ax.set_xlabel("Embedding dimension")
    ax.set_title(f"{VARIANT_DISPLAY[variant]}", fontsize=8)

    for i in range(pct.shape[0]):
        for j in range(pct.shape[1]):
            v = pct.iloc[i, j]
            color = "black" if 45 < v < 90 else "white"
            ax.text(j, i, f"{v:.0f}", ha="center", va="center",
                    fontsize=7, color=color)

    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(f"% of full-dim {_metric_label(metric)}", fontsize=8)
    cbar.ax.tick_params(labelsize=7)

    fig.tight_layout()
    fig.savefig(out_path, format="pdf", bbox_inches="tight")
    plt.close(fig)


def plot_mrl_vs_pca_gap(
    df: pd.DataFrame, out_path: Path, metric: str = "ndcg_at_10"
) -> None:
    """Bar chart: B-truncate minus A-PCA at each dim, mean across datasets."""
    import matplotlib.pyplot as plt
    setup_matplotlib_acl()

    sub = df[df["variant"].isin(["runA-pca", "runB-truncate"])]
    pivot = sub.groupby(["variant", "dim"])[metric].mean().unstack("variant")
    pivot["gap"] = pivot["runB-truncate"] - pivot["runA-pca"]
    pivot = pivot.sort_index(ascending=False)

    fig, ax = plt.subplots(figsize=(ACL_COL_WIDTH, ACL_COL_WIDTH * 0.65))

    dims = pivot.index.tolist()
    gaps = pivot["gap"].tolist()
    colors = ["#2ca02c" if g > 0 else "#d62728" for g in gaps]

    x = list(range(len(dims)))
    ax.bar(x, gaps, color=colors, edgecolor="black", linewidth=0.5)
    ax.axhline(0, color="black", linewidth=0.5)

    ax.set_xticks(x)
    ax.set_xticklabels([str(d) for d in dims])
    ax.set_xlabel("Embedding dimension")
    ax.set_ylabel(f"{_metric_label(metric)} gap")

    for i, g in enumerate(gaps):
        offset = max(abs(g) * 0.08, 0.005)
        if g >= 0:
            ax.text(i, g + offset, f"{g:+.3f}",
                    ha="center", va="bottom", fontsize=7)
        else:
            ax.text(i, g - offset, f"{g:+.3f}",
                    ha="center", va="top", fontsize=7)

    ax.grid(True, axis="y", alpha=0.3, linewidth=0.5)
    ax.set_axisbelow(True)

    # Headroom for the value labels
    y_min, y_max = ax.get_ylim()
    pad = (y_max - y_min) * 0.15
    ax.set_ylim(y_min - pad if y_min < 0 else y_min,
                y_max + pad if y_max > 0 else y_max)

    fig.tight_layout()
    fig.savefig(out_path, format="pdf", bbox_inches="tight")
    plt.close(fig)
